### ISSUE TITLE
Dart 3 incompatibility issue

### ISSUE THREAD

**Issue by Besufikad17** [damoonrashidi/bitalarm#13]
Hey there, I cloned bitalarm to run and test it locally and when I tried to install packages using `flutter pub get` and I got dart sdk incompatible error. Then I changed the sdk version and some of the packages version to the latest, but I found out one of the packages called `nav_router` is dart 3 incompatible. Have u considered making bitalarm compatible with dart 3 by using other routing packages? Thanks in advance

**Comment by damoonrashidi** [comment]
Hey @Besufikad17  I have no short term plans, but I did write bitalarm v1 for the alpha version of flutter, and did a rewrite for version 2. So I'll most likely do another version for dart3 as soon as I have a good enough understanding of the rust/flutter bridge, since that looks fun.

I'll be more than happy to approve a PR that adds dart3 compatibility though
