### ISSUE TITLE
it is deprecated?

### ISSUE THREAD

**Issue by AlbCM** [damoonrashidi/bitalarm#4]
Are you going to update this project?

**Comment by damoonrashidi** [comment]
Good question @AlbCM! I really should get it up and running with the newer versions of flutter. I've been wanting to use it myself recently. I'll start and revamp next week.

**Comment by botemple** [comment]
Will you able to start a project that base flutter with real decentralize wallet. and cross platform.

**Comment by damoonrashidi** [comment]
what platforms are you suggesting @botemple, it would be fairly easy to target mobile and desktop (unsure of iOS since I don't have an iOS device nor am I super excited to go through the iOS release process).

For the decentralized wallet I was thinking I'm not gonna build an actual wallet but rather let you link your existing wallets, like the app does today, and it will calculate your total combined wallet value in a given FIAT.

**Comment by damoonrashidi** [comment]
Working on v2 now @AlbCM , but it's a total re-write. The old code can still be found in the `legacy/v1` branch. The new code has a lot better flutter best practices imo tho, but very little functionality right now.
